#use "topfind"
#require "base64"

let add_chan buf chan =
  try
    while true do
      let line = input_line chan in
      Buffer.add_string buf line;
      Buffer.add_char   buf '\n'
    done
  with End_of_file ->
    ()

let () =
  let setup  = Sys.argv.(1) in
  let content_setup =
    let ic = open_in_bin setup in
    let bs = Buffer.create 4098 in
    add_chan bs ic;
    close_in ic;
    Buffer.contents bs
  in
  let base64_setup =
    match Base64.encode content_setup with
    | Ok b -> b
    | Error (`Msg err) ->
      failwith (Printf.sprintf "While encoding cygwin-setup.exe : %s" err)
  in
  Printf.printf
    {|(* THIS FILE IS AUTOMATICALLY GENERATED, EDIT src/state/dune & shell/embedCygwin.ml INSTEAD *)
let base64 =
  "%s"
let drop location =
  if Sys.win32 || Sys.cygwin then
  let content = Base64.decode_exn base64 in
  let oc = open_out_bin location in
  output_string oc content;
  close_out oc|}
    base64_setup
