#!/bin/sh

set -ue

UNTRACKED="
appveyor_build.cmd
appveyor.patch
appveyor_test.sh
appveyor.yml
AUTHORS
CONTRIBUTING.md
.gitattributes
.github
.gitignore
ISSUE_TEMPLATE.md
.ocamlinit
.ocp-indent
.ocplint
README.md
.travis-ci.sh
.travis.yml
master_changes.md
"
changelog=master_changes.md
diffile=/tmp/diff

git fetch origin $GITHUB_BASE_REF --depth=1 --quiet
echo "> base commit"
git show origin/$GITHUB_BASE_REF --format=oneline -s

git diff origin/$GITHUB_BASE_REF --name-status --diff-filter=AM > $diffile
updated=0
if [ -z "`grep -s $changelog $diffile`" ] ; then
  updated=1
fi

echo "> all changes"
cat $diffile

for untrack in $UNTRACKED ; do
  sed -i "/$untrack/d" $diffile
done

echo "> kept changes"
cat $diffile

num_changes=`wc -l $diffile | cut -f 1 -d ' '`

if [ $num_changes -ne 0 ] ; then
  if [ $updated -eq 0 ] ; then
    echo "[32mChangelog updated[0m"
  else
    echo "[31mPlease update changelog in master_changes.md[0m"
    exit 1
  fi
else
  echo "[33mCommited files not concerned by changelog[0m"
fi
