.TH OPAM-SEARCH 1 "September 03, 2012" "Opam Manual" "Version 0.4"
.SH NAME
.PP
opam-search - Search into the package database
.SH SYNOPSIS
.PP
\f[I]opam search\f[] <packagepattern>...
.SH DESCRIPTION
.PP
This command displays the list of available packages that match one of
the <packagepattern>s specified as arguments.
This command is almost identical to the \f[I]opam list\f[] command,
except that packages get selected if their descriptions match the
pattern, in addition of their names.
.SH OPTIONS
.TP
.B <packagepattern>...
Search for packages whose name or description matches at least one
<packagepattern>.
The case is not taken into account.
.RS
.RE
.SH SEE ALSO
.PP
\f[B]opam-list\f[](1) \f[B]opam-info\f[](1)
.SH OPAM
.PP
Part of the opam(1) suite
.SH AUTHORS
OCamlPro.
