.TH OPAM-UPGRADE 1 "September 03, 2012" "Opam Manual" "Version 0.4"
.SH NAME
.PP
opam-upgrade - Upgrade installed packages
.SH SYNOPSIS
.PP
\f[I]opam upgrade\f[]
.SH DESCRIPTION
.PP
This command upgrades the installed packages to their latest available
versions.
More precisely, this command call the dependency solver to find a
consistent state where \f[B]most\f[] of the installed packages are
upgraded to their latest versions.
.SH OPTIONS
.PP
None
.SH SEE ALSO
.PP
\f[B]opam-remote\f[](1) \f[B]opam-update\f[](1)
.SH OPAM
.PP
Part of the opam(1) suite
.SH AUTHORS
OCamlPro.
