.TH OPAM-REINSTALL 1 "10/09/2012" "opam 0.6.0" "OPAM Manual"
.SH NAME
.PP
opam-reinstall - Re-install packages
.SH SYNOPSIS
.PP
\f[I]opam reinstall\f[] <package>...
.SH DESCRIPTION
.PP
This command does \f[I]opam remove\f[] followed by \f[I]opam
install\f[].
.SH PARAMETERS
.TP
.B <package>...
Package(s) to be installed.
.RS
.RE
.SH SEE ALSO
.PP
\f[B]opam-install\f[](1), \f[B]opam-remove\f[](1),
\f[B]opam-switch\f[](1), \f[B]opam-list\f[](1)
.SH OPAM
.PP
Part of the opam(1) suite
.SH AUTHORS
OCamlPro.
