.\" Pipe this output to groff -man -Tutf8 | less
.\"
.TH "OPAM-ADMIN-MAKE" 1 "" "Opam-admin 1.1.2" "Opam-admin Manual"
.\" Disable hyphenantion and ragged-right
.nh
.ad l
.SH NAME
.P
opam\-admin\-make \- Initialize a repo for serving files.
.SH SYNOPSIS
.P
\fBopam\-admin make\fR [\fIOPTION\fR]... [\fIPKG\fR]...
.SH ARGUMENTS
.TP 4
\fIPKG\fR
Names of the packages to include in the repo.
.SH OPTIONS
.TP 4
\fB\-d\fR, \fB\-\-dryrun\fR
Simply display the possible actions instead of executing them.
.TP 4
\fB\-\-debug\fR
Display debug messages.
.TP 4
\fB\-g\fR, \fB\-\-generate\-checksums\fR
Automatically correct the wrong archive checksums.
.TP 4
\fB\-\-help\fR[=\fIFMT\fR] (default=pager)
Show this help in format \fIFMT\fR (pager, plain or groff).
.TP 4
\fB\-i\fR, \fB\-\-index\fR
Only build indexes, not package archives.
.TP 4
\fB\-r\fR, \fB\-\-recursive\fR
Recurse among the transitive dependencies.
.TP 4
\fB\-\-resolve\fR
A more advanced version of `\-\-recursive': will attempt to resolve your installation with all dependencies in the best way possible and build the archives accordingly.
.TP 4
\fB\-\-version\fR
Show version information.