.TH OPAM-PIN 1 "10/09/2012" "opam 0.6.0" "OPAM Manual"
.SH NAME
.PP
opam-pin - Pin a package to a specific version
.SH SYNOPSIS
.PP
\f[I]opam pin\f[] <package> <version>
.PP
\f[I]opam pin\f[] <package> <path>
.PP
\f[I]opam pin\f[] <package> none
.SH DESCRIPTION
.PP
This command will "pin" a package to a specific version, or use a
specific source path for installing and upgrading the package.
Using \f[I]opam pin <package> none\f[] will undo the "pinned" status of
<package>.
.SH PARAMETERS
.TP
.B <package>
Specify package to pin or unpin.
.RS
.RE
.TP
.B <version>
Pin the selected package to a specific version.
.RS
.RE
.TP
.B <path>
Use the specified path for installing or upgrading the package.
This means that from now on, \f[I]opam install\f[] and \f[I]opam
upgrade\f[] will use the specified path to install (respectively
upgrade) the package.
.RS
.RE
.TP
.B none
Unpin the package, i.e.
use the default sources and version for the package.
.RS
.RE
.SH OPAM
.PP
Part of the opam(1) suite
.SH AUTHORS
OCamlPro.
