.TH OPAM-UPLOAD 1 "10/09/2012" "opam 0.6.0" "OPAM Manual"
.SH NAME
.PP
opam-upload - Upload a new package to a remote repository
.SH SYNOPSIS
.PP
\f[I]opam upload\f[] -opam <opam-file> -descr <descr-file> -archive
<name.version.tar.gz> [-repo <repository>]
.SH DESCRIPTION
.PP
This command uploads an already built package to a remote repository, if
the remote repository is not read-only.
.SH PARAMETERS
.TP
.B -opam <opam-file>
Specify the .opam file that will be uploaded to
repo://packages/name.version/opam
.RS
.RE
.TP
.B -descr <descr-file>
Specify the .descr file that will be uploaded to
repo://packages/name.version/descr
.RS
.RE
.TP
.B -archive <name.version.tar.gz>
Specify the archive that will be uploaded to
repo://archives/name.version+opam.tar.gz
.RS
.RE
.SH OPTIONS
.TP
.B -repo <repository>
Specify the repository to upload to.
Defaults to the default repository.
.RS
.RE
.SH SEE ALSO
.PP
\f[B]opam-remote\f[](1), \f[B]opam-upgrade\f[](1)
.SH OPAM
.PP
Part of the opam(1) suite
.SH AUTHORS
OCamlPro.
