.TH OPAM-UPDATE 1 "September 03, 2012" "Opam Manual" "Version 0.4"
.SH NAME
.PP
opam-update - Synchronize repositories
.SH SYNOPSIS
.PP
\f[I]opam update\f[]
.SH DESCRIPTION
.PP
This command updates each repository that has been previously set up by
the \f[I]opam init\f[] or \f[I]opam remote\f[] commands.
The list of packages that can be upgraded will be printed out, and the
user can use \f[I]opam upgrade\f[] to upgrade those.
.SH SEE ALSO
.PP
\f[B]opam-init\f[](1) \f[B]opam-remote\f[](1) \f[B]opam-upgrade\f[](1)
.SH OPAM
.PP
Part of the opam(1) suite
.SH AUTHORS
OCamlPro.
