.\" Pipe this output to groff -man -Tutf8 | less
.\"
.TH "OPAM-LIST" 1 "" "Opam 0.8.2" "Opam Manual"
.\" Disable hyphenantion and ragged-right
.nh
.ad l
.SH NAME
.P
opam\-list \- Display the list of available packages.
.SH SYNOPSIS
.P
\fBopam list\fR [\fIOPTION\fR]... [\fIPATTERNS\fR]...
.SH DESCRIPTION
.P
This command displays the list of available packages, or the list of installed packages if the \fB\-\-installed\fR switch is used.
.P
Unless the \fB\-\-short\fR switch is used, the output format displays one package per line, and each line contains the name of the package, the installed version or \-\- if the package is not installed, and a short description.
.P
The full description can be obtained by doing \fBopam info <package>\fR. You can search through the package descriptions using the \fBopam search\fR command.
.SH ARGUMENTS
.TP 4
\fIPATTERNS\fR
List of package patterns.
.SH OPTIONS
.TP 4
\fB\-i\fR, \fB\-\-installed\fR
List installed packages only.
.TP 4
\fB\-\-no\-base\-packages\fR
Do not install base packages (useful for testing purposes).
.TP 4
\fB\-s\fR, \fB\-\-short\fR
Output the names of packages separated by one whitespace instead of using the usual formatting.
.SH COMMON OPTIONS
.P
These options are common to all commands.
.TP 4
\fB\-\-debug\fR
Print debug message on stdout.
.TP 4
\fB\-\-help\fR[=\fIFMT\fR] (default=pager)
Show this help in format \fIFMT\fR (pager, plain or groff).
.TP 4
\fB\-q\fR, \fB\-\-quiet\fR
Be quiet.
.TP 4
\fB\-r\fR \fIROOT\fR, \fB\-\-root\fR=\fIROOT\fR (absent=/Users/tgazagna/.opam)
Use \fIROOT\fR as the current root path.
.TP 4
\fB\-s\fR \fISWITCH\fR, \fB\-\-switch\fR=\fISWITCH\fR
Use \fISWITCH\fR as the current compiler switch.
.TP 4
\fB\-v\fR, \fB\-\-verbose\fR
Be more verbose.
.TP 4
\fB\-\-version\fR
Show version information.
.TP 4
\fB\-y\fR, \fB\-\-yes\fR
Disable interactive mode and answer yes to all questions that would otherwise beasked to the user.
.SH AUTHORS
.P
Thomas Gazagnaire <thomas.gazagnaire@ocamlpro.com>
.SH BUGS
.P
Check bug reports at https://github.com/OCamlPro/opam/issues.