.\" Pipe this output to groff -man -Tutf8 | less
.\"
.TH "OPAM-HELP" 1 "" "Opam 0.8.2" "Opam Manual"
.\" Disable hyphenantion and ragged-right
.nh
.ad l
.SH NAME
.P
opam\-help \- display help about opam and opam commands
.SH SYNOPSIS
.P
\fBopam help\fR [\fIOPTION\fR]... [\fITOPIC\fR]
.SH DESCRIPTION
.P
Prints help about opam commands
.SH ARGUMENTS
.TP 4
\fITOPIC\fR
The topic to get help on. `topics' lists the topics.
.SH COMMON OPTIONS
.TP 4
\fB\-\-debug\fR
Print debug message on stdout.
.TP 4
\fB\-q\fR, \fB\-\-quiet\fR
Be quiet.
.TP 4
\fB\-r\fR \fIROOT\fR, \fB\-\-root\fR=\fIROOT\fR (absent=/Users/tgazagna/.opam)
Use \fIROOT\fR as the current root path.
.TP 4
\fB\-s\fR \fISWITCH\fR, \fB\-\-switch\fR=\fISWITCH\fR
Use \fISWITCH\fR as the current compiler switch.
.TP 4
\fB\-v\fR, \fB\-\-verbose\fR
Be more verbose.
.TP 4
\fB\-y\fR, \fB\-\-yes\fR
Disable interactive mode and answer yes to all questions that would otherwise beasked to the user.
.SH OPTIONS
.TP 4
\fB\-\-help\fR[=\fIFMT\fR] (default=pager)
Show this help in format \fIFMT\fR (pager, plain or groff).
.TP 4
\fB\-\-man\-format\fR=\fIFMT\fR (absent=pager)
Show output in format \fIFMT\fR (pager, plain or groff).
.TP 4
\fB\-\-version\fR
Show version information.