.TH OPAM 1 "20/02/2013" "OPAM 1.0.1" "OPAM Manual"
.SH NAME
.PP
opam-check - a Tool check that OPAM repositories are consistent
.SH DESCRIPTION
.PP
See \f[I]opam-check --help\f[] for more information.
.SH SEE ALSO
.PP
\f[B]opam\f[](1)
.SH LINKS
.IP \[bu] 2
\f[B]http://opam.ocamlpro.com\f[]
.SH OPAM
.PP
Part of the opam(1) suite
.SH AUTHORS
OCamlPro.
