.\" Pipe this output to groff -man -Tutf8 | less
.\"
.TH "OPAM-CONFIG" 1 "" "Opam 0.8.2" "Opam Manual"
.\" Disable hyphenantion and ragged-right
.nh
.ad l
.SH NAME
.P
opam\-config \- Display configuration options for packages
.SH SYNOPSIS
.P
\fBopam config\fR [\fIOPTION\fR]... \fICOMMAND\fR [\fIARG\fR]...
.SH DESCRIPTION
.P
This command uses opam state to output information on how to use installed libraries, updating the user’s PATH, and substitute variables used in opam packages.
.P
Apart from \fBopam config env\fR, most of these commands are used by opam internally, and thus are of limited interest for the casual user.
.SH ARGUMENTS
.TP 4
\fICOMMAND\fR
Name of the sub\-command. See the \fBCOMMANDS\fR section for more info.
.SH OPTIONS
.TP 4
\fB\-c\fR, \fB\-\-csh\fR
Use csh\-compatible output mode.
.TP 4
\fB\-r\fR, \fB\-\-rec\fR
Recursive query.
.SH COMMANDS
.TP 4
\fBenv\fR
returns the environment variables PATH, MANPATH, OCAML_TOPLEVEL_PATH and CAML_LD_LIBRARY_PATH according to the current selected compiler. The output of this command is meant to be evaluated by a shell, for example by doing \fBeval `opam config env`\fR.
.TP 4
\fBvar\fR
returns the value associated with the given variable.
.TP 4
\fBlist\fR
returns the list of all variables defined in the listed packages (no package = all).
.TP 4
\fBsubst\fR
substitutes variables in the given files.
.TP 4
\fBincludes\fR
returns include options.
.TP 4
\fBbytecomp\fR
returns bytecode compile options.
.TP 4
\fBasmcomp\fR
returns assembly compile options.
.TP 4
\fBbytelink\fR
returns bytecode linking options.
.TP 4
\fBasmlink\fR
returns assembly compile options.
.SH COMMON OPTIONS
.P
These options are common to all commands.
.TP 4
\fB\-\-debug\fR
Print debug message on stdout.
.TP 4
\fB\-\-help\fR[=\fIFMT\fR] (default=pager)
Show this help in format \fIFMT\fR (pager, plain or groff).
.TP 4
\fB\-q\fR, \fB\-\-quiet\fR
Be quiet.
.TP 4
\fB\-r\fR \fIROOT\fR, \fB\-\-root\fR=\fIROOT\fR (absent=/Users/tgazagna/.opam)
Use \fIROOT\fR as the current root path.
.TP 4
\fB\-s\fR \fISWITCH\fR, \fB\-\-switch\fR=\fISWITCH\fR
Use \fISWITCH\fR as the current compiler switch.
.TP 4
\fB\-v\fR, \fB\-\-verbose\fR
Be more verbose.
.TP 4
\fB\-\-version\fR
Show version information.
.TP 4
\fB\-y\fR, \fB\-\-yes\fR
Disable interactive mode and answer yes to all questions that would otherwise beasked to the user.
.SH MORE HELP
.P
Use `opam \fICOMMAND\fR \-\-help' for help on a single command.
.sp -1
.P
Use `opam help patterns' for help on patch matching.
.sp -1
.P
Use `opam help environment' for help on environment variables.
.SH AUTHORS
.P
Thomas Gazagnaire <thomas.gazagnaire@ocamlpro.com>
.SH BUGS
.P
Check bug reports at https://github.com/OCamlPro/opam/issues.