.TH OPAM-UPLOAD 1 "September 03, 2012" "Opam Manual" "Version 0.4"
.SH NAME
.PP
opam-upload - Upload a new package to a remote repository
.SH SYNOPSIS
.PP
\f[I]opam upload\f[] -opam <opam-file> -descr <descr-file> -archive
<name.version.tar.gz> [-repo <repository>]
.SH DESCRIPTION
.PP
TODO: add description
.SH PARAMETERS
.TP
.B -opam <opam-file>
Specify the .opam file to use.
.RS
.RE
.TP
.B -descr <descr-file>
Specify the .descr file to use.
.RS
.RE
.TP
.B -archive <name.version.tar.gz>
.RS
.RE
.SH SEE ALSO
.PP
\f[B]opam-remote\f[](1) \f[B]opam-upgrade\f[](1)
.SH OPAM
.PP
Part of the opam(1) suite
.SH AUTHORS
OCamlPro.
