.TH OPAM 1 "20/02/2013" "OPAM 1.0.1" "OPAM Manual"
.SH NAME
.PP
opam-mk-repo - a Tool to Build OPAM Repositories
.SH DESCRIPTION
.PP
See \f[I]opam-mk-repo --help\f[] for more information.
# SEE ALSO
.PP
\f[B]opam\f[](1)
.SH LINKS
.IP \[bu] 2
\f[B]http://opam.ocamlpro.com\f[]
.SH OPAM
.PP
Part of the opam(1) suite
.SH AUTHORS
OCamlPro.
