URL_cppo = https://github.com/ocaml-community/cppo/archive/v1.8.0.tar.gz
MD5_cppo = a197cb393b84f6b30e0ff55080ac429b

URL_extlib = https://github.com/ygrek/ocaml-extlib/releases/download/1.8.0/extlib-1.8.0.tar.gz
MD5_extlib = 43fb3bf2989671af1769147b1171d080

URL_base64 = https://github.com/mirage/ocaml-base64/releases/download/v3.5.1/base64-3.5.1.tbz
MD5_base64 = bfdd16aa8c136412878109df8791fc01

URL_re = https://github.com/ocaml/ocaml-re/archive/refs/tags/1.14.0.tar.gz
MD5_re = 03f4a83100cb9229a796b85c698076e1

URL_cmdliner = https://erratique.ch/software/cmdliner/releases/cmdliner-1.3.0.tbz
MD5_cmdliner = 662936095a1613d7254815238e11793f

URL_ocamlgraph = https://github.com/backtracking/ocamlgraph/releases/download/2.2.0/ocamlgraph-2.2.0.tbz
MD5_ocamlgraph = 3195404bc06fce560d5336d7614028bc

URL_cudf = https://gitlab.com/irill/cudf/-/archive/v0.10/cudf-v0.10.tar.gz
MD5_cudf = ed8fea314d0c6dc0d8811ccf860c53dd

URL_dose3 = https://gitlab.com/irill/dose3/-/archive/7.0.0/dose3-7.0.0.tar.gz
MD5_dose3 = bc99cbcea8fca29dca3ebbee54be45e1

URL_mccs = https://github.com/ocaml-opam/ocaml-mccs/releases/download/1.1+19/mccs-1.1+19.tar.gz
MD5_mccs = f852da188bf7de20e64be2fce0e48e0a

URL_opam-0install-cudf = https://github.com/ocaml-opam/opam-0install-cudf/releases/download/v0.5.0/opam-0install-cudf-0.5.0.tar.gz
MD5_opam-0install-cudf = 75419722aa839f518a25cae1b3c6efd4

URL_0install-solver = https://github.com/0install/0install/releases/download/v2.18/0install-2.18.tbz
MD5_0install-solver = 030edc9b1d3676c06d51397ffb5a737d

URL_opam-file-format = https://github.com/ocaml/opam-file-format/releases/download/2.2.0/opam-file-format-2.2.0.tar.gz
MD5_opam-file-format = 5b65ea84fa2e60e89c2c9f2ca3203e31

include Makefile.dune

URL_stdlib-shims = https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz
MD5_stdlib-shims = 09db7af8b4a3a96048a61cb6ae2496ef

URL_spdx_licenses = https://github.com/kit-ty-kate/spdx_licenses/releases/download/v1.4.0/spdx_licenses-1.4.0.tar.gz
MD5_spdx_licenses = 6accb8029f7401f1face7d4f7efa5fa7

URL_uutf = https://erratique.ch/software/uutf/releases/uutf-1.0.4.tbz
MD5_uutf = 19c8e6d8ae6c70116495a7d44ac75f3d

URL_jsonm = https://erratique.ch/software/jsonm/releases/jsonm-1.0.2.tbz
MD5_jsonm = bb21574ddd58543120430ff306b462e6

URL_sha = https://github.com/djs55/ocaml-sha/releases/download/v1.15.4/sha-1.15.4.tbz
MD5_sha = 08bc953d9a26380bc220b05d680791fb

URL_swhid_core = https://github.com/OCamlPro/swhid_core/archive/refs/tags/0.1.tar.gz
MD5_swhid_core = 77d88d4b1d96261c866f140c64d89af8

URL_menhir = https://gitlab.inria.fr/fpottier/menhir/-/archive/20250903/archive.tar.gz
MD5_menhir = 5ecb7f71cf374147d3d3137c6e2fe382

URL_patch = https://github.com/hannesm/patch/releases/download/v3.0.0/patch-3.0.0.tar.gz
MD5_patch = 75aca1ed79a9807e4d4fc6c85aa31b0f
