# NB If minimum OCaml version for Dune changes, update DUNE_SECONDARY in configure.ac
URL_dune-local = https://github.com/ocaml/dune/releases/download/3.19.0/dune-3.19.0.tbz
MD5_dune-local = 49cd8594162ce913e85f78b533284b30
