URL_cppo = https://github.com/ocaml-community/cppo/releases/download/v1.6.6/cppo-v1.6.6.tbz
MD5_cppo = b13afeea6631d7c9b61f95bfd984a542

$(call PKG_SAME,cppo)

URL_extlib = https://ygrek.org/p/release/ocaml-extlib/extlib-1.7.7.tar.gz
MD5_extlib = 2c620993aecd4b31b3a362b21b55dd94

$(call PKG_SAME,extlib)

URL_re = https://github.com/ocaml/ocaml-re/releases/download/1.9.0/re-1.9.0.tbz
MD5_re = bddaed4f386a22cace7850c9c7dac296

$(call PKG_SAME,re)

URL_cmdliner = http://erratique.ch/software/cmdliner/releases/cmdliner-1.0.2.tbz
MD5_cmdliner = ab2f0130e88e8dcd723ac6154c98a881

$(call PKG_SAME,cmdliner)

URL_ocamlgraph = http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.8.tar.gz
MD5_ocamlgraph = 9d71ca69271055bd22d0dfe4e939831a

$(call PKG_SAME,ocamlgraph)

URL_cudf = https://github.com/ocaml/opam-source-archives/raw/main/cudf-0.9.tar.gz
MD5_cudf = a4c0e652e56e74c7b388a43f9258d119

$(call PKG_SAME,cudf)

URL_dose3 = https://gitlab.com/irill/dose3/-/archive/5.0.1/dose3-5.0.1.tar.gz
MD5_dose3 = a81080f36f477fdebf63c4a979e251cd

$(call PKG_SAME,dose3)

URL_mccs = https://github.com/AltGr/ocaml-mccs/archive/1.1+13.tar.gz
MD5_mccs = 13504d3b5dcbf0bdc6d95a62de20af4a

$(call PKG_SAME,mccs)

URL_opam-file-format = https://github.com/ocaml/opam-file-format/archive/2.1.3.tar.gz
MD5_opam-file-format = b805562dd2d86fc3c8e6d47884fd1da6

$(call PKG_SAME,opam-file-format)

URL_result = https://github.com/janestreet/result/archive/1.4.tar.gz
MD5_result = d3162dbc501a2af65c8c71e0866541da

$(call PKG_SAME,result)

URL_dune-local = https://github.com/ocaml/dune/releases/download/1.6.3/dune-1.6.3.tbz
MD5_dune-local = 1212a36547d25269675d767c38fecf5f

$(call PKG_SAME,dune-local)

URL_PKG_findlib = http://download.camlcity.org/download/findlib-1.8.1.tar.gz
MD5_PKG_findlib = 18ca650982c15536616dea0e422cbd8c

URL_PKG_ocamlbuild = https://github.com/ocaml/ocamlbuild/archive/0.14.0.tar.gz
MD5_PKG_ocamlbuild = a7bf2fe594cd16907807c756b14d501f

URL_PKG_topkg = http://erratique.ch/software/topkg/releases/topkg-0.9.1.tbz
MD5_PKG_topkg = 8978a0595db1a22e4251ec62735d4b84

URL_seq = https://github.com/c-cube/seq/archive/0.1.tar.gz
MD5_seq = 0e87f9709541ed46ecb6f414bc31458c

# This is necessary as long as a patch is used to rename seq.ml and seq.mli
ensure-seq-patched.stamp: seq.stamp
	rm -f seq/src/seq.ml seq/src/seq.mli

$(call PKG_SAME,seq)
