FROM multiarch/alpine:%TARGET_TAG%
# May need configuration on the host:
#    docker run --rm --privileged multiarch/qemu-user-static:register --reset
LABEL Description="opam release builds" Vendor="OCamlPro" Version="1.0"

RUN apk add gcc g++ make coreutils openssl

RUN addgroup -S opam && adduser -S opam -G opam -s /bin/sh

ADD https://caml.inria.fr/pub/distrib/ocaml-4.12/ocaml-4.12.0.tar.gz /root/

WORKDIR /root
RUN tar xzf ocaml-4.12.0.tar.gz
WORKDIR ocaml-4.12.0
RUN sed -i 's/gnueabi/*eabi/' configure
RUN sed -i 's/musl/musl*/' configure
RUN ./configure %CONF% -prefix /usr/local
RUN make world opt.opt && make install && rm -rf /root/ocaml-4.12.0 /root/ocaml-4.12.0.tar.gz

RUN apk add patch

ENV PATH /usr/local/bin:/usr/bin:/bin
USER opam
WORKDIR /home/opam/
CMD tar xz >&2 && \
    cd opam-full-${VERSION} >&2 && \
    echo "(${LINKING})" > src/client/linking.sexp && \
    ./configure --with-mccs --with-vendored-deps >&2 && \
    make opam >&2 && \
    strip opam >&2 && \
    cat opam
