FROM ghcr.io/kit-ty-kate/alpine:%TARGET_TAG%
# May need configuration on the host:
#    docker run --rm --privileged multiarch/qemu-user-static:register --reset
LABEL Description="opam release builds" Vendor="OCamlPro" Version="1.0"

RUN apk add gcc g++ make coreutils openssl patch

RUN addgroup -S opam && adduser -S opam -G opam -s /bin/sh

ENV PATH /usr/local/bin:/usr/bin:/bin
USER opam
WORKDIR /home/opam/
CMD { tar xz && \
      cd opam-full-${VERSION} && \
      make compiler && \
      ./configure --with-vendored-deps --with-mccs && \
      echo "(${LINKING})" > src/client/linking.sexp && \
      make opam-stripped ; \
    } >&2 && \
    cat opam-stripped
